application: everydaycomputing
version: uno
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /public
  static_dir: public

- url: /.*
  script: everydaycomputing.APP
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest